# 書き方
# [[plugins]]
# repo = 'Githubのリポジトリ'
# hook_add = 
# hook_source = 
# hook_post_source = 
# hook_post_update = 
# hook_done_update = 

# |   hook の名前    |              実行されるタイミング            | lazy OFF | lazy ON |
# | hook_add         | プラグインが dein.vim によって追加されたとき |    OK    |    OK   |
# | hook_source      | プラグインが読み込まれる直前                 |    NG    |    OK   |
# | hook_post_source | プラグインが読み込まれた直後                 |    NG    |    OK   |
# | hook_post_update | プラグインが更新された直後                   |    OK    |    OK   |
# | hook_done_update | プラグイン全ての更新が終わった直後           |    OK    |    OK   |

# | 遅延ロード |            ロードされるタイミング            |                            例                             |
# | on_cmd     | コマンドが実行される時にロード               | on_cmd = ['Command'] / on_cmd = ['Command1', 'Command2']  |
# | on_event   | イベントが実行される時にロード               | on_event = ['Event'] / on_event = ['Event1', 'Event2']    |
# | on_func    | 関数が実行される時にロード                   | on_func = ['Func'] / on_func = ['Func1', 'Func2']         |
# | on_ft      | 指定されたファイルタイプの時にロード         | on_ft = ['FileType'] / on_ft = ['FileType1', 'FileType2'] |
#                                                             | on_ft = ['ft'] / on_ft = ['ft1', 'ft2']                   |
# | on_i       | インサートモード移行時にロード (0以外で有効) | on_i = 1 / on_i = 2                                       |

# ブラウザオープン
[[plugins]]
repo = 'tyru/open-browser.vim'

# vim上でGit操作
[[plugins]]
repo = 'tpope/vim-fugitive'

# 閉じ補完
[[plugins]]
repo = 'cohama/lexima.vim'

# ツリー表示
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    nnoremap <silent> <Leader>f :NERDTreeToggle<CR>
    nnoremap <silent> <Leader>ff :NERDTreeFocus<CR>
    let g:NERDTreeIgnore = ['\.o$', '\.git$']
    let g:NERDTreeShowHidden = 1
'''

# カーソル移動
[[plugins]]
repo = 'easymotion/vim-easymotion'

# 置換プレビュー
[[plugins]]
repo = 'markonm/traces.vim'

# 選択範囲を検索
[[plugins]]
repo = 'thinca/vim-visualstar'
hook_add = '''
    map * <Plug>(visualstar-*)N
    map # <Plug>(visualstar-#)N
'''

# インデントレベルの可視化
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
    let g:indentLine_fileTypeExclude = ['help', 'nerdtree']
    let g:indentLine_enabled = 1
    let g:indentLine_color_term = 166
'''

# カーソルにある単語のハイライト
[[plugins]]
repo = 'RRethy/vim-illuminate'
hook_add = '''
    let g:illuminate_delay = 300
    let g:illuminate_highlightUnderCursor = 0
"    augroup illuminate_augroup
"        autocmd!
"        autocmd VimEnter * hi link illuminatedWord Visual
"    augroup END
'''

# 選択した文字に該当する文字をすべてハイライトにする
[[plugins]]
repo = 't9md/vim-quickhl'
hook_add = '''
    nmap <Space>m <Plug>(quickhl-manual-this)
    xmap <Space>m <Plug>(quickhl-manual-this)
    nmap <Space>r <Plug>(quickhl-manual-reset)
    xmap <Space>r <Plug>(quickhl-manual-reset)
    nmap <Space>c <Plug>(quickhl-manual-clear)
    vmap <Space>c <Plug>(quickhl-manual-clear)
'''

# Google翻訳
[[plugins]]
repo = 'skanehira/translate.vim'
